apiVersion: apps/v1
kind: Deployment
metadata:
  name: crasher
  labels:
    app: crasher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crasher
  template:
    metadata:
      labels:
        app: crasher
    spec:
      containers:
      - name: crasher
        image: rosskukulinski/crashing-app
        ports:
        - containerPort: 80