newrelic-infrastructure:
  integrations_config:
    - name: nri-rabbitmq.yaml
      data:
        # Run auto discovery to find pods with label "app=rabbitmq"
        # https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
        discovery:
          command:
            # Use the following optional arguments:
            # --namespaces: Comma separated list of namespaces to discover pods on
            # --tls: Use secure (TLS) connection
            # --port: Port used to connect to the kubelet. Default is 10255
            exec: /var/db/newrelic-infra/nri-discovery-kubernetes
            match:
              label.component: rabbitmq
        integrations:
          - name: nri-rabbitmq
            env:
              # using the discovered IP as the hostname address
              HOSTNAME: ${discovery.ip}
              PORT: 15672
              USERNAME: user
              PASSWORD: bitnami
              # MANAGEMENT_PATH_PREFIX: <(Optional) rabbitmq management path prefix>
              # CA_BUNDLE_DIR: <(Optional) ca bundle directory>
              # CA_BUNDLE_FILE: <(Optional)ca bundle file>
              NODE_NAME_OVERRIDE: minikube-workshop
              # CONFIG_PATH: <(Optional) /path/to/config/file/rabbitmq.conf>
              # USE_SSL: <(Optional) bool>
              QUEUES: '["message"]'
              # QUEUES_REGEXES: <(Optional) json array of regexes, matching queue names will be collected>
              EXCHANGES: '["default"]'
              # EXCHANGES_REGEXES: <(Optional) json array of regexes, matching exchange names will be collected>
              # VHOSTS: <(Optional) json array of vhost names to collect>
              # VHOSTS_REGGEXES: <(Optional) json array of regexes, entities assigned to vhosts matching a regex will be collected>
            labels:
              env: workshop
              role: rabbitmq