apiVersion: v1
kind: Pod
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  containers:
  - image: docker.pkg.github.com/newrelic-experimental/kubernetes-demo-apps/loadgen:latest
    name: loadgen
  restartPolicy: Always
