apiVersion: v1
kind: Pod
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  containers:
  - image: ghcr.io/kidk/kubernetes-demo-apps-loadgen:latest
    name: loadgen
  restartPolicy: Always
