apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
      # annotations:
      #   fluentbit.io/exclude: "true"
    spec:
      containers:
      - image: bschmitt769/kubernetes-demo-apps-loadgen:1.0
        imagePullPolicy: Always
        name: loadgen
        command:
          - ./loadgen.sh
          - "8888"
      restartPolicy: Always